# Behaviorbot config. See https://github.com/behaviorbot/ for more information.
# Note: Please Don't edit this file directly.
# Edit https://github.com/benbalter/behaviorbot-config instead.

# Configuration for update-docs - https://github.com/behaviorbot/update-docs
updateDocsComment: >
  "Thanks for opening this pull request! If you are making any changes to the user-facing functionality, please be sure to update the documentation in the `README` or `docs/` folder alongside your change. :heart:"

# Configuration for request-info - https://github.com/behaviorbot/request-info
requestInfoReplyComment: >
  Thanks for this. Do you mind providing a bit more info about what problem you're trying to solve?
requestInfoLabelToAdd: more-information-needed

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
firstPRMergeComment: >
  Congrats on merging your first pull request! We here at behaviorbot are proud of you!
