title: Jekyll style guide
description: An opinionated guide to common Jekyll design patterns and anti-patterns.
repository: benbalter/jekyll-style-guide

collections:
  docs:
    output: true
    permalink: /:path/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - node_modules
  - script
  - README.md
  - LICENSE.md
  - package.json
  - Gemfile
  - tmp
